tiff(file="Fig5_C.tif",res=150,width=7000,height=1500)
par(mfrow=c(1,1))
par(mai=c(0.5,0.5,0.5,0), mgp=c(15,2,0.1))
pop<-read.table("Ad_name.list",as.is=T)
q<-read.table("ID_6_1.qopt")
ord<-order(pop[,1])
barplot(t(q)[,ord],col=rainbow(8),space=0,border=NA,xlab="",ylab="",las=2,cex.lab=4,font.axis=2,yaxt="n")
axis(2,cex.axis=2.5,lwd=6,line=-8)
abline(v=cumsum(sapply(unique(pop[ord,1]),function(x){sum(pop[ord,1]==x)})),col=1,lwd=1.5,las=2)
dev.off()
